### ISSUE TITLE
Depend on System.Numerics.Vectors

### ISSUE THREAD

**Issue by yufeih** [studio-nine/Nine.Geometry#1]
`System.Numerics.Vectors` is the core type of Vectors and Matrix in corefx. Using types under that package allows us to be SIMD ready and interoperable with other libraries. We should drop the types under MonoGame

**Comment by ChillyFlashER** [comment]
I tried to use the package before, but it seems there is not a portable version available. 

If we did use it, we are missing structures like BoundingSphere, BoundingBox etc. We could create some basic structs that just contains the methods we are using, although I dislike having the structures here.

**Comment by ChillyFlashER** [comment]
[Related MonoGame Issue](https://github.com/mono/MonoGame/issues/3781)
