### ISSUE TITLE
Implementation does use ref optimization

### ISSUE THREAD

**Issue by yufeih** [studio-nine/Nine.Geometry#3]
Take this as an example:

``` csharp

        public void Contains(ref BoundingBox boundingBox, out ContainmentType result) => result = this.Contains(boundingBox);
        
        public ContainmentType Contains(BoundingBox boundingBox)
        {
            ContainmentType result;
            Intersection.Intersect(ref boundingBox, ref this, out result);
            return result;
        }

```

BoundingBox.Contains(ref BoundingBox)  calls Contains(BoundingBox), which causes the box to be copied.

In addition, not all contains method has a ref counter part. E.g., we have a Contains(BoundingFrustum) but there is no Contains(ref BoundingFrustum)

The suggestion is to move all these containment test methods into Intersection, each method has a Contains(struct) and Contains(ref struct) pair. BoundingBox only contain basic methods that does not take a ref structures, like Contains(Vector3) and Intersects(BoundingBox).

**Comment by ChillyFlashER** [comment]
Would you consider this fixed? Other than that not all the methods are implemented yet.

**Comment by yufeih** [comment]
Yeah, looks awesome
