### ISSUE TITLE
ISpatialQueryable for 2D and 3D?

### ISSUE THREAD

**Issue by ChillyFlashER** [studio-nine/Nine.Geometry#4]
Should there be two different types of _ISpatialQueryable_ one for 2D and one for 3D?

So QuadTree would only work with 2D and Octree would only work with 3D.

**Comment by yufeih** [comment]
How about replacing `ISpatialQueryable` with just a ``BoundingBox` parameter and a `Move` operation?

The purpose of `ISpatialQueryable` is to abstract things that have a bounds and will notify changes when the bounds has changed. IMO, the old *Engine Nine* uses too much abstractions to control behaviors inside out.

I propose we make Quadtree/Octree passive:

```csharp
public class Quadtree<T>
{
    void Clear();
    QuadtreeNode<T> Add(BoundingRectangle bounds, T value);
    bool Remove(QuadtreeNode<T> node);
    bool Move(QuadtreeNode<T> node, BoundingRectangle bounds);
    int Find(BoundingRectangle rectangle, T[] output, int startIndex);
}

public struct QuadtreeNode<T>
{
    public readonly T Value;
    public readonly BoundingRectangle Bounds;
}
```

**Comment by yufeih** [comment]
To allow concurrent reads, `Find` method can take an optional `Stack<int>` object to put the traverse stack, the caller is responsible to allocate the stack.

```csharp
int Find(BoundingRectangle rectangle, T[] output, int startIndex, Stack<int> traverseStack = null);
```

**Comment by ChillyFlashER** [comment]
Should id's be exposed instead of `DynamicTreeNode<T>` from `Add` and `Remove`?

**Comment by yufeih** [comment]
Let's expose `Id`: `int Add(BoundingRectangle, T)`

**Comment by ChillyFlashER** [comment]
Closing refer to #5 instead.
