### ISSUE TITLE
Replace Octree/Quadtree with dynamic bounding volumn hierarchy

### ISSUE THREAD

**Issue by yufeih** [studio-nine/Nine.Geometry#5]
An example of dynamic BVH can be found in _Farseer Physics_ [DynamicTree.cs](https://github.com/tinco/Farseer-Physics/blob/9d2a0bbc3de793359d536f7237725fbd20c55dbf/SourceFiles/Collision/DynamicTree.cs)

**Comment by ChillyFlashER** [comment]
I should have tagged my latest commit 3df86d6 where I added _DynamicTree3D<T>_.

I'd say that the only thing left is to fix raycast.
