### ISSUE TITLE
Targeted Frameworks

### ISSUE THREAD

**Issue by ChillyFlashER** [studio-nine/Nine.Geometry#7]
What frameworks would be best to support?

Apparently `dnx451 == dotnet5.4` which changed a while ago, so that should be fixed.
And `dnxcore50` falls under `dotnet` from what I understand.

**Comment by yufeih** [comment]
They are still working on the NET Standard TFM, till then, we can just use net45 to target desktop

**Comment by ChillyFlashER** [comment]
I switched the project to .NET Standard 1.6. 
I didn't fix the appveyor build so it will fail.
